name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push(머지)될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Corepack 활성화 (Yarn 관리 도구)
      - name: Enable Corepack
        run: corepack enable

      # 3. 요구 Yarn 버전 설치 및 활성화
      - name: Use Yarn 4.5.3
        run: corepack prepare yarn@4.5.3 --activate

      # 4. Yarn Zero Install (PnP 환경)
      - name: Install dependencies (PnP)
        run: yarn install --immutable

      # 5. Yarn PnP 환경에서 빌드 실행
      - name: Build project
        run: |
          yarn build

      # 6. GitHub Pages로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vite 빌드 출력 디렉토리
          full_commit_message: ${{ github.event.head_commit.message }}


