name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push(머지)될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Corepack 활성화 (Yarn 관리 도구)
      - name: Enable Corepack
        run: corepack enable

      # 3. 요구 Yarn 버전 설치 및 활성화
      - name: Use Yarn 4.5.3
        run: corepack prepare yarn@4.5.3 --activate

      # 4. Yarn Zero Install (PnP 환경)
      - name: Install dependencies (PnP)
        run: yarn install --immutable

      # 5. Yarn PnP 환경에서 빌드 실행
      - name: Build project & deploy
        run: |
          yarn build
          yarn deploy

