name: Deploy to GitHub Pages (Zero Install)

on:
  push:
    branches:
      - main  # main 브랜치에 push(머지)될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 사용할 Node.js 버전
          cache: 'yarn'  # Yarn Zero Install 환경에서 캐시 활성화

      # 3. Yarn Zero Install 실행
      - name: Install dependencies (Zero Install)
        run: yarn install --immutable

      # 4. 빌드 실행
      - name: Build project
        run: yarn build

      # 5. GitHub Pages로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vite 빌드 출력 디렉토리
